name: Run CI jobs for stage 3 (3.ci)

on:
  push:
    paths-ignore:
      - 'scripts/**' 
      - '**/docs/**'

env:
  TEST_REPORT_PATH: "reports/coverage-html"
  TESTS_PATH: "tests"
  PYTHON_VERSION : "3.11"

jobs:
####################################
## python code linting (ruff) 
####################################
  code-linting:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format"
        continue-on-error: true

####################################
## test case 
####################################
  test-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read ## needed for checkout
      actions: write ## needed to upload artifacts
      pages: write ## needed to deploy to GitHub Pages
      id-token: write ## needed for OIDC token
    steps:
      - name: git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Get latest stage 
        id: latest
        uses: ./.github/actions/find-latest

      - name: Setting up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ${{ steps.latest.outputs.latest-stage-folder }}
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "missing requirements.txt file, aborting"; exit 1; fi

      - name: Generate coverage report for tests 
        run: |
          pip install pytest pytest-cov
          cd ${{ steps.latest.outputs.latest-stage-folder }}
          python -m pytest --cov=tests --cov-report=term-missing --cov-report=html:${{ env.TEST_REPORT_PATH }}

      - name: Upload HTML coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./${{ steps.latest.outputs.latest-stage-folder }}/${{ env.TEST_REPORT_PATH }}/
          retention-days: 14

      - name: Upload latest stage pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./${{ steps.latest.outputs.latest-stage-folder }}/${{ env.TEST_REPORT_PATH }}/

####################################
## documentation generation (pdoc)
####################################
  documentation-generation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only generate documentation on main branch
    steps:
      - name: git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Get latest stage 
        id: latest
        uses: ./.github/actions/find-latest

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ${{ steps.latest.outputs.latest-stage-folder }}
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "missing requirements.txt file, aborting"; exit 1; fi

      - name: generate code documentation using pdoc
        run: |
          echo ${{ steps.latest.outputs.latest-stage-folder }}
          pwd
          pip install pdoc
          cd ${{ steps.latest.outputs.latest-stage-folder }}
          pwd
          pdoc app/ --output-dir ../docs --docformat google

####################################
## github page deploy
####################################
  deploy-pages:
    environment:
      name: github-pages
    needs: 
      - test-coverage
      - documentation-generation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only deploy pages on main branch
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4